### ISSUE TITLE
misleading figure title in inversion notebook

### ISSUE THREAD

**Issue by stevejpurves** [equinor/segyio-notebooks#12]
I have been reviewing the 01_seismic_inversion.ipynb notebook and note that the figures have a suptitle "Colored Inversion".

Is this an error / misleading? I understood from the implementation that this is a [linear] inversion based on the statistical wavelet estimate made.

In order to be colored inversion, we would need to use a log spectrum to design an inversion operator and apply that which in not what is happening in this code as far as I can see.

Should the mention of to "Colored Inversion" be removed here?

**Comment by mrava87** [comment]
Hi Steve, totally agree :)

I should have probably used relative instead of colored just to avoid any confusion. I am happy for you to fix it a do a PR or I can do it?

**Comment by stevejpurves** [comment]
@mrava87 I would had but I don't have the data local to re-run and update the figures, so it might be faster for you if you have?

**Comment by mrava87** [comment]
Its fixed now

Btw estimating acoustic impedance via inversion like done in this notebook is much better than coloured inversion as you can more easily add priors and any type of regularization/preconditioner you want :)

**Comment by mrava87** [comment]
@stevejpurves have a look and let me know if this is good for you

**Comment by stevejpurves** [comment]
looks great @mrava87 thanks, it's a small change but when people just skim the text/figures then they'l go away with the right idea about what this does 👍
