### ISSUE TITLE
Estimating the convolutional operator

### ISSUE THREAD

**Issue by lperozzi** [equinor/segyio-notebooks#9]
Many thanks for these useful notebooks!

I have a small question about the seismic  [inversion notebooks](https://github.com/equinor/segyio-notebooks/blob/master/notebooks/pylops/01_seismic_inversion.ipynb). Following the Lancaster and Whitcombe (2000) article and the [TLE tutorials](https://wiki.seg.org/wiki/Colored_inversion) the operator is derived from well logs, in this example is derived directly from the data. 

```
# estimate wavelet spectrum
wav_est_fft = np.mean(np.abs(np.fft.fft(d[..., :500], nfft, axis=-1)), axis=(0, 1))
fwest = np.fft.fftfreq(nfft, d=dt/1000)
```

Is this would not affect the final results?

**Comment by mrava87** [comment]
Hi,
there are many ways of deriving the wavelet, in this case we did not want to focus on that aspect and went for the simplest way (statistical wavelet) but you could of course replace it with a well-tie wavelet. Either approaches are very common, the choice of which one to use generally depends on the data quality and availability of wells.

The focus here was to invert the post-stack convolutional modelling for a large dataset. While the approach you mention is a valid one, what we do here is more advanced and it is what lies at the core of most deterministic relative (and absolute) inversion tools used in industry.

**Comment by lperozzi** [comment]
Hi @mrava87, many thanks for the explanations!
